"""
Django settings for WageCalc project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%px5$(od1)&7v2g#99r!+udwk$@7jo$0ohpc9go^*d8kxr(hy7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
SIMPLEUI_DEFAULT_THEME = 'x-green.css'
# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wage.apps.WageConfig',
    'captcha',
    'dadmin.apps.DadminConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WageCalc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# AUTH_USER_MODEL = 'wage.MyUser'
WSGI_APPLICATION = 'WageCalc.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wagecalc',
        'HOST': '172.16.6.85',
        'PORT': '3306',
        'USER': 'wagecalc',
        'PASSWORD': 'SHKtpJfixJFt5dNR',
        'OPTIONS': {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
# 导入导出
# IMPORT_EXPORT_USE_TRANSACTIONS = True

USE_TZ = False
# USE_L10N = False
#
# DATETIME_FORMAT = 'Y/m/d H:i:s'
#
# DATE_FORMAT = 'Y/m'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['基础信息', '导入报表', '工资汇总', '离职薪资', '离职面谈台账', '权限认证'],  # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'app': 'wage',
        'name': '基础信息',
        'icon': 'el-icon-more',
        'models': [{
            'name': '员工',
            'icon': 'el-icon-user-solid',
            'url': 'wage/wageemployee/'
        }, {
            'name': '部门',
            'icon': 'el-icon-phone',
            'url': 'wage/wagedeptment/'
        }, {
            'name': '岗位',
            'icon': 'el-icon-s-cooperation',
            'url': 'wage/wageposition/'
        }, {
            'name': '费用项目',
            'icon': 'el-icon-s-comment',
            'url': 'wage/wageexpense/'
        }, {
            'name': '基地',
            'icon': 'el-icon-position',
            'url': 'wage/wagebase/'
        }, {
            'name': '技能津贴',
            'icon': 'el-icon-water-cup',
            'url': 'wage/wageskill/'
        }, {
            'name': '管理津贴',
            'icon': 'el-icon-postcard',
            'url': 'wage/wagemanage/'
        }
        ]
    }, {
        'app': 'wage',
        'name': '工资汇总',
        'icon': 'el-icon-lock',
        'models': [{
            'name': '月度工资汇总表',
            'icon': 'el-icon-connection',
            'url': 'wage/wagemonth/'
        }
        ]
    }, {
        'app': 'wage',
        'name': '离职薪资',
        'icon': 'el-icon-s-flag',
        'models': [{
            'name': '离职薪资汇总',
            'icon': 'el-icon-s-opportunity',
            'url': 'wage/wageleave/'
        }
        ]
    },
        {
            'app': 'wage',
            'name': '导入报表',
            'icon': 'el-icon-upload2',
            'models': [{
                'name': '费用导入',
                'icon': 'el-icon-s-promotion',
                'url': 'wage/wageexpenseinto/'
            }, {
                'name': '绩效导入',
                'icon': 'el-icon-s-flag',
                'url': 'wage/wageperformanceinto/'
            }, {
                'name': '固定工资导入',
                'icon': 'el-icon-s-data',
                'url': 'wage/wagefixwage/'
            }, {
                'name': '上传日志',
                'icon': 'el-icon-finished',
                'url': 'wage/wagelog/'
            }
            ]
        },
        {
            'app': 'wage',
            'name': '离职面谈台账',
            'icon': 'el-icon-folder',
            'models': [{
                'name': '离职理由',
                'icon': 'el-icon-tickets',
                'url': 'wage/leavereason/'
            }, {
                'name': '面谈台账',
                'icon': 'el-icon-document',
                'url': 'wage/leaveaccount/'
            }
            ]
        },
        {
            'app': 'auth',
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [{
                'name': '用户',
                'icon': 'fa fa-user',
                'url': 'auth/user/'
            }, {
                'name': '组',
                'icon': 'fas fa-users-cog',
                'url': 'auth/group/'
            }]
        }]
}
